name: Google Sheets API Interaction

on:
  push:
    branches:
      - main  # Ejecuta el flujo en cada push a la rama principal

jobs:
  run-google-sheets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Usa la versión más reciente

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Asegúrate de instalar Node.js
        with:
          node-version: '16'  # Puedes usar '18' si es compatible

      - name: Install dependencies
        run: npm install

      - name: Run script to interact with Google Sheets
        run: |
          node script.js
        env:
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
