name: Google Sheets API Interaction

on:
  push:
    branches:
      - main

jobs:
  run-google-sheets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Verifica el código fuente

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # O '18' si es compatible

      # Elimina el paso npm install ya que no usas npm
      # - name: Install dependencies
      #   run: npm install

      - name: Run script to interact with Google Sheets
        run: |
          node script.js  # Cambia "script.js" al nombre de tu archivo principal
        env:
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
