name: Google Sheets Update

on:
  push:
    branches:
      - main  # Cambia a la rama que estás usando

jobs:
  update-sheets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Run script to update Google Sheets
      env:
        CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_ID }}
        PRIVATE_KEY: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  
      run: |
        # Obtener un token de acceso usando el CLIENT_EMAIL y PRIVATE_KEY
        TOKEN=$(curl -s -X POST -H "Content-Type: application/json" \
        -d '{
          "iss": "'"$CLIENT_EMAIL"'",
          "scope": "https://www.googleapis.com/auth/spreadsheets",
          "aud": "https://oauth2.googleapis.com/token",
          "exp": '"$(( $(date +%s) + 3600 ))"',
          "iat": $(date +%s)
        }' https://www.googleapis.com/oauth2/v4/token | jq -r .access_token)

        # Usar el token de acceso para actualizar Google Sheets
        curl -X POST \
          -H "Authorization: Bearer $TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "range": "INFORMES!A2:G",  # Cambia el rango según sea necesario
            "majorDimension": "ROWS",
            "values": [
              [data.nombre, data.participa, data.estudios, data.horas, data.credito, data.comentarios]  # Cambia estos valores según sea necesario
            ]
          }' \
          "https://sheets.googleapis.com/v4/spreadsheets/12AhQg1rVBLM7-kOrqaHYK7wrA7ewgZNL_qNpSsXUy3Q/values:append?valueInputOption=RAW"
